version: '3.8'

services:
  php-apache:
    build: .
    container_name: php_mongo_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
