name: PHP Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports: ['27017:27017']
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpass
        options: >-
          --health-cmd "mongosh --eval 'db.stats()'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker-compose -f docker-compose.yml up --build -d

    - name: Test PHP app (optional)
      run: |
        curl --retry 5 --retry-delay 5 --fail http://localhost:8000
